---
abstract: 'Event based SCGI server'
author:
  - 'Kevin Jones <kevinj@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.85'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-SCGI
no_index:
  directory:
    - inc
    - t
recommends:
  Coro: 5.17
  EV: 0
requires:
  AnyEvent: 5.2
resources:
  license: http://dev.perl.org/licenses/
version: 1.1
